config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only:[:create, :show, :edit, :index, :update, :destroy] do
    resources :book_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end
  resources :relationships, only:[:create, :destroy]
  resources :users, only:[:show, :edit, :index, :update,]
  root 'homes#top'
  get'home/about' => 'homes#about'
  get'users/:id/follow' => 'users#follow', as:'follow'
  get'users/:id/follower' => 'users#follower', as:'follower'
  get 'search' => 'searchs#search', as:'search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  validates :introduction, length: {maximum: 50}
  validates :name, length: {in: 2..20}
  validates :name, presence: true

  #フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  #through:sourceとセットのこと多い。多対多で中間テーブルが複数ある場合、throughオプションで中間テーブルを指定すれば、経路を決めることができる。
  #source:class_nameとほぼ同じらしい。throughを使うような中間テーブルがある場合はsource。一対多のような中間テーブルを使わない場合はclass_nameらしい。
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  #class_name:一つのモデルに対して二つのアソシエーション経路を組む場合に多用
  #foreign_key:難しい
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  #検索機能でselectの時に記述
  def User.search(term, how_search)
    if how_search == "perfect"
      User.where(name: term)
    elsif how_search == "front"
      User.where(['name LIKE ?', "#{term}%"])
    elsif how_search == "back"
      User.where(['name LIKE ?', "%#{term}"])
    elsif how_search == "part"
      User.where(['name LIKE ?', "%#{term}%"])
    else
      User.all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
  	#マイページ
    @user = User.find(params[:id])
    #新規投稿
    @book = Book.new
    #current_userのデータだけ引っ張ってくる
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user.id == current_user.id
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully'
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def follow
    @user = User.find(params[:id])
    @follow_users = @user.followings
  end

  def follower
    @user = User.find(params[:id])
    @follower_users = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidetable.html.erb
<div class="user-image">
  <%= attachment_image_tag @user, :profile_image, :fill,60,60, format:'jpeg', class:"profile_img", fallback:"no_image.jpg",size:'100x100' %>
</div>

<table class = "table table-hover">
  <thead>
    <tr>
      <th>name</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th>introduction</th>
      <td><%= @user.introduction %></td>
    </tr>
    <tr>
      <th>follows</th>
      <td>
        <%= link_to follow_path(@user), :method => :get do %>
          <%= @user.followings.count %></td>
        <% end %>
    </tr>
    <tr>
      <th>follower</th>
      <td>
        <%= link_to follower_path(@user), :method => :get do %>
          <%= @user.followers.count %>
        <% end %>
      </td>
    </tr>
  </thead>
</table>

app/views/users/edit.html.erb
<div class = "container">
  <div class = "row">
    <h1>User info</h1>
      <% if @user.errors.any? %>
        <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
        <% @user.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <%end%>
      <%end%>
      <div class = "form-group">
        <%= form_for(@user) do |f| %>
          <div class = "field">
            <label class = "edit-name">Name</label>
            <%= f.text_field :name %>
          </div>
          <div class = "field">
            <label class = "edit-image">Image</label>
            <%= f.attachment_field :profile_image, class:"user-edit-form" %>
          </div>
          <div class = "field">
            <label class = "edit-introduction">Introduction</label>
            <%= f.text_area :introduction %>
          </div>
          <div class = "action">
            <%= f.submit "Update User" %>
          </div>
        <%end%>
      </div>
  </div>
</div>

app/views/users/follow.html.erb
<h1>Follow Users</h1>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @follow_users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill,60,60, format:'jpeg', class:"profile_img", fallback:"no_image.jpg",size:'40x40' %></td>
          <td><%= user.name %></td>
          <td><p>フォロー数:<%= user.followings.count %></p></td>
          <td><p>フォロワー数:<%= user.followers.count %></p></td>
          <td>
            <% if current_user %>
              <% if current_user.following?(user) %>
                  <%= link_to 'フォローを外す', relationship_path(relationship: current_user.relationships.find_by(follow_id: user.id)), method: :delete %>
              <% else %>
                  <%= link_to 'フォローする', relationships_path(id: user), method: :post %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <%end%>
    </tbody>
  </table>

app/views/users/follower.html.erb
<h1>Follower Users</h1>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @follower_users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill,60,60, format:'jpeg', class:"profile_img", fallback:"no_image.jpg",size:'40x40' %></td>
          <td><%= user.name %></td>
          <td><p>フォロー数:<%= user.followings.count %></p></td>
          <td><p>フォロワー数:<%= user.followers.count %></p></td>
          <td>
            <% if current_user.following?(user) %>
                <%= link_to 'フォローを外す', relationship_path(relationship: current_user.relationships.find_by(follow_id: user.id)), method: :delete %>
            <% else %>
                <%= link_to 'フォローする', relationships_path(id: user), method: :post %>
            <% end %>
          </td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <%end%>
    </tbody>
  </table>

app/views/users/index.html.erb
<div class = "container">
   <div class = "row">
  	    <div class = "col-xs-3">
          <!--ユーザー情報表示-->
          <h1>User info</h1>
          <!--profile画像を埋め込み-->
          <!--ユーザー情報もろもろ-->
          <%= render 'users/sidetable' %>
          <!---->
          
          <div class = "row">
            <!--フォロー・button機能-->
            <%= render 'relationships/follow_button', user: @user %>
            <!--パーシャル利用-->
          </div>

  	      <h2>New book</h2>
           <!--新規投稿フォーム-->
           <%= render 'books/newbook', book: @book %>
        </div>
        <!--current_userの投稿一覧-->
        <div class = "col-xs-9">
          <!--検索フォーム-->
          <%= render 'searchs/search' %>
        <h1>Users</h1>
  	        <table class = "table table-hover">
  	          <thead>
  	            <tr>
                  <th>image</th>
  	              <th>name</th>
  	              <th></th>
                  <th></th>
                  <th></th>
                  <th></th>
  	            </tr>
              </thead>
              <tbody>
                <% @users.each do |user| %>
                  <tr>
                    <td><%= attachment_image_tag user, :profile_image, :fill,60,60, format:'jpeg', class:"profile_img", fallback:"no_image.jpg",size:'40x40' %></td>
                    <td><%= user.name %></td>
                    <td><p>フォロー数:<%= user.followings.count %></p></td>
                    <td><p>フォロワー数:<%= user.followers.count %></p></td>

                    <td>
                      <% unless user == current_user %>
                        <% if current_user.following?(user) %>
                          <%= link_to 'フォローを外す', relationship_path(id: current_user.relationships.find_by(follow_id: user.id)), method: :delete %>
                        <% else %>
                            <%= link_to 'フォローする', relationships_path(id: user.id), method: :post %>
                        <% end %>
                      <% end %>
                    </td>
                    <td><%= link_to "Show", user_path(user.id) %></td>
                  </tr>
                <%end%>
              </tbody>
  	        </table>
  	    </div>
    </div>
</div>

app/views/users/show.html.erb
<div class = "container">
  <% if flash[:notice] %>
    <div class = "flash">
      <%= flash[:notice]%>
    </div>
  <%end%>
   <div class = "row">
  	    <div class = "col-xs-3">
          <!--ユーザー情報表示-->
          <h1>User info</h1>
          <!--profile画像を埋め込み-->
          <!--ユーザー情報もろもろ-->
          <%= render 'users/sidetable' %>
          <!---->

          <div class = "row">
            <!--フォロー機能,editへのbutton-->
              <%= render 'relationships/follow_button', user: @user %>
            <!--パーシャル利用-->
          </div>
          <!--ここまで-->

  	      <h2>New book</h2>
           <!--新規投稿フォーム-->
           <%= render 'books/newbook', book: @book %>
        </div>
        <!--current_userの投稿一覧-->
        <div class = "col-xs-9">
          <!--検索フォーム-->
          <%= render 'searchs/search' %>

          <h1>Books</h1>
  	        <table class = "table table-hover">
  	          <thead>
  	            <tr>
                  <th></th>
  	              <th>Title</th>
  	              <th>Opinion</th>
  	            </tr>
              </thead>
              <tbody>
                <% @books.each do |book| %>
                  <tr>
                    <td><%= attachment_image_tag @user, :profile_image, :fill,60,60, format:'jpeg', class:"profile_img", fallback:"no_image.jpg",size:'40x40' %></td>
                    <td><%= link_to book.title, book_path(book.id)  %></td>
                    <td><%= book.body %></td>
                  </tr>
                <%end%>
              </tbody>
  	        </table>
  	    </div>
    </div>
</div>