config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only:[:create, :show, :edit, :index, :update, :destroy] do
    resources :book_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end
  resources :relationships, only:[:create, :destroy]
  resources :users, only:[:show, :edit, :index, :update,]
  root 'homes#top'
  get'home/about' => 'homes#about'
  get'users/:id/follow' => 'users#follow', as:'follow'
  get'users/:id/follower' => 'users#follower', as:'follower'
  get 'search' => 'searchs#search', as:'search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  #いいねしているかどうか
  def favorited_by?(user)
  	favorites.where(user_id: user.id).exists?
  end
  #
  validates :body, length: {maximum: 200}
  validates :title, presence: true
  validates :body, presence: true

  #検索機能
  def Book.search(term, how_search)
    if how_search == "perfect"
      Book.where(title: term)
    elsif how_search == "front"
      Book.where(['title LIKE ?', "#{term}%"])
    elsif how_search == "back"
      Book.where(['title LIKE ?', "%#{term}"])
    elsif how_search == "part"
      Book.where(['title LIKE ?', "%#{term}%"])
    else
      Book.all
    end
  end
  #
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def set_book
    @book = current_user.books.find(params[:id])
  end

  def show
    @book = Book.find(params[:id])
    @comment = BookComment.new
    @book_new = Book.new
    @user = @book.user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully'
      redirect_to book_path(@book.id)
    else
      @book_new = Book.new
      @user = current_user
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless @book.user.id == current_user.id
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully'
      redirect_to book_path(@book.id)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def index
    @book =Book.new
    @user = current_user
    @users = User.all
    @books = Book.page(params[:page]).reverse_order
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newbook.html.erb
<%= form_for(book) do |f| %>
  <div class = "form-group row">
    <%= f.label 'Title'%>
    <%= f.text_field :title, class:'form-control col-md-12' %>
  </div>
  <div class = "form-group row">
    <%= f.label 'Opinion'%>
    <%= f.text_area :body, class:'form-control col-md-12' %>
  </div>
  <div class = "form-group row">
    <%= f.submit"Create Book", class:"btn btn-primary col-md-12"%>
  </div>
<%end%>

app/views/books/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-md-6 col-md-offset-3">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
          <% @book.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <%end%>
        <%end%>
      <div class = "form-group">
        <%= form_for(@book) do |f|%>
          <div class = "field row">
            <label calss = "title">Title</label>
            <%= f.text_field :title, class:"col-md-12"%>
          </div>
          <div class = "field row">
            <label class = "opinion">Opinion</label>
            <%= f.text_area :body, class:"col-md-12"%>
          </div>
          <div class = "action row">
            <%= f.submit "Update Book", class:"btn btn-primary col-md-12" %>
          </div>
        <%end%>
      </div>
      <%= link_to "Show", book_path(@book.id)%>
      |
      <%= link_to "Back", books_path %>
    </div>
    <div class = "col-md-3"></div>
  </div>
</div>

app/views/books/index.html.erb
<div class = "container">
   <div class = "row">
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <% @book.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <%end%>
      <%end%>
  	    <div class = "col-xs-3">
          <!--ユーザー情報表示-->
          <h1>User info</h1>
          <!--ユーザー情報もろもろ-->
          <%= render 'users/sidetable' %>
          <!---->

          <!--ここまで-->
          <div class = "row">
            <!--フォロー・button機能-->
            <%= render 'relationships/follow_button', user: @user %>
            <!--パーシャル利用-->
          </div>

  	       <h2>New book</h2>
           <!--新規投稿フォーム-->
           <%= render 'books/newbook', book: @book %>
        </div>
  	    <div class = "col-xs-9">
          <!--検索フォーム-->
          <%= render 'searchs/search' %>
          <h1>Books</h1>
  	        <table class = "table table-hover">
              <thead>
  	            <tr>
                  <th></th>
  	              <th>Title</th>
  	              <th>Opinion</th>
  	            </tr>
              </thead>
              <tbody>
                <% @books.each do |book|%>
                  <tr>
                    <td>
                      <%= link_to user_path(book.user) do %>
                       <%= attachment_image_tag book.user, :profile_image, :fill,60,60, format:'jpeg', class:"profile_img", fallback:"no_image.jpg",size:'40x40' %>
                      <% end %>
                    </td>
                    <td><%= link_to book.title, book_path(book.id) %></td>
                    <td><%= book.body %></td>

                    <!--いいね機能等-->
                    <td>
                      <% if book.favorited_by?(current_user) %>
                      <li>
                          <%= link_to book_favorites_path(book.id), method: :delete do %>
                          <i class="far fa-heart" aria-hidden="true" style="color: red;"></i>
                          <%= book.favorites.count %>
                          <% end %>
                      </li>
                      <% else %>
                      <li>
                          <%= link_to book_favorites_path(book.id), method: :post do %>
                          <i class="far fa-heart" aria-hidden="true"></i>
                          <%= book.favorites.count %>
                          <% end %>
                      </li>
                      <% end %>
                    </td>
                      <!--ここまで-->

                    <td>コメント数:<%= book.book_comments.count %></td>
                  </tr>
                <%end%>
                <%= paginate @books, class:"paginate" %>
              </tbody>
  	        </table>
  	    </div>
    </div>
</div>

app/views/books/show.html.erb
<div class = "container">
   <div class = "row">
      <% if flash[:notice] %>
        <div class = "flash">
          <%= flash[:notice]%>
        </div>
      <%end%>
  	    <div class = "col-xs-3">
          <!--ユーザー情報表示-->
          <h1>User info</h1>
          <!--ユーザー情報もろもろ-->
          <%= render 'users/sidetable', user: @user %>
          <!--ここまで-->
          <%= link_to edit_user_path(@book.user), :method => :get do %>
            <i class = "glyphicon glyphicon-wrench aria-hidden=true btn btn-default col-md-12"></i>
          <%end%>

  	       <h2>New book</h2>
           <!--新規投稿フォーム-->
           <%= render 'books/newbook', book: @book_new %>
        </div>
  	    <div class = "col-xs-9">
          <h1>Book detail</h1>
          <!--ここから投稿テーブル-->
  	        <table class = "table table-hover">
              <thead>
  	            <tr>
                  <th></th>
  	              <th>Title</th>
  	              <th>Opinion</th>
                  <th></th>
                  <th></th>
  	            </tr>
              </thead>
              <tbody>
                  <tr>
                    <td>
                      <%= attachment_image_tag @book.user, :profile_image, :fill,60,60, format:'jpeg', class:"profile_img", fallback:"no_image.jpg",size:'40x40' %><br>
                      <%= link_to @book.user.name, user_path(@book.user.id) %>
                    </td>
                    <td><%= @book.title %></td>
                    <td><%= @book.body %></td>

                    <!--いいね機能-->
                    <td>
                      <% if @book.favorited_by?(current_user) %>
                      <li>
                          <%= link_to book_favorites_path(@book.id), method: :delete do %>
                          <i class="far fa-heart" aria-hidden="true" style="color: red;"></i>
                          <%= @book.favorites.count %>
                          <% end %>
                      </li>
                      <% else %>
                      <li>
                          <%= link_to book_favorites_path(@book.id), method: :post do %>
                          <i class="far fa-heart" aria-hidden="true"></i>
                          <%= @book.favorites.count %>
                          <% end %>
                      </li>
                      <% end %>
                    </td>
                    <!--ここまで-->

                    <td>カウント数:<%= @book.book_comments.count %></td>

                    <% if @book.user == current_user %>
                      <td><%= link_to"Edit", edit_book_path(@book.id), class:"btn btn-success" %></td>
                      <td><%= link_to"Destroy", book_path(@book.id), class:"btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか?" %></td>
                    <%end%>
                  </tr>
              </tbody>
  	        </table>
            <!--ここまで-->

            <!--ここからコメントform-->
            <%= form_for [@book,@comment] do |f| %>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_area :comment, class:"form-control"%><span><%= f.submit"送信" %></span>
                </div>
              </div>
            <% end %>
            <!--ここまで-->

            <!--コメント一覧-->
            <table class="table hover">
              <thead>
                <tr>
                  <th></th>
                  <th>Comment</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              <% @book.book_comments.each do |comment| %>
                <tr>
                  <td>
                    <%= link_to user_path(@book.user) do %>
                     <%= attachment_image_tag @book.user, :profile_image, :fill,60,60, format:'jpeg', class:"profile_img", fallback:"no_image.jpg",size:'40x40' %>
                    <% end %>
                  </td>
                  <td><%= comment.comment %></td>
                  <td>
                    <% if comment.user == current_user %>
                      <%= link_to "destroy", book_book_comment_path(@book.id), class:"btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか?" %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
            <!--ここまで-->
  	    </div><!--col9のdiv-->
    </div><!--rowのdiv-->
</div>