config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only:[:create, :show, :edit, :index, :update, :destroy] do
    resources :book_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end
  resources :relationships, only:[:create, :destroy]
  resources :users, only:[:show, :edit, :index, :update,]
  root 'homes#top'
  get'home/about' => 'homes#about'
  get'users/:id/follow' => 'users#follow', as:'follow'
  get'users/:id/follower' => 'users#follower', as:'follower'
  get 'search' => 'searchs#search', as:'search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController

	def search
		#Viewのformで取得したパラメータをモデルに渡す
		if params[:option] == "user"
			@users = User.search(params[:term], params[:choice])
			#render 'users/index',indexに検索結果のuserだけ表示される。
		elsif params[:option] == "book"
			@books = Book.search(params[:term], params[:choice])
			@books = @books.page(params[:page])
		end
	end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/_search.html.erb
<% if user_signed_in? %>
	<div class="search">
		<%= form_tag(search_path, :method => 'get') do %>
			<%= text_field_tag :term %>
			<%= select_tag(:option, options_for_select([["user","user"],["book","book"]])) %><!--["ブラウザに表示される文字",""コントローラーに送られてくる値]-->
			<%= select_tag(:choice, options_for_select([["完全一致", "perfect"],["前方一致", "front"],["後方一致","back"],["部分一致","part"]]))%>
			<%= submit_tag '検索' %>
		<% end %>
	</div>
<% end %>

app/views/searchs/search.html.erb
<h1>検索結果</h1>

<table class="table">
	<% if @users.present? %>
	    <tr>
	    	<th>name</th>
	    	<th></th>
	    </tr>
		<% @users.each do |user| %>
		<tr>
			<td><%= user.name %></td>
			<td><%= button_to "詳細", user_path(user.id), method: :get, class:"btn btn-success" %></td>
		</tr>
	<% end %>
	<% elsif @books.present? %>
	    <tr>
	    	<th>Name</th>
	    	<th>Title</th>
	    	<th></th>
		<% @books.each do |book| %>
			<tr>
				<td><%= book.user.name %></td>
				<td><%= link_to book.title, book_path(book.id) %></td>
				<td><%= book.created_at %></td>
			</tr>
		<% end %>
		<%= paginate @books, class:"paginate" %>
	<% else %>
	　　<h1>検索結果はありません</h1>
	<% end %>

</table>