config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only:[:create, :show, :edit, :index, :update, :destroy] do
    resources :book_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end
  resources :relationships, only:[:create, :destroy]
  resources :users, only:[:show, :edit, :index, :update,]
  root 'homes#top'
  get'home/about' => 'homes#about'
  get'users/:id/follow' => 'users#follow', as:'follow'
  get'users/:id/follower' => 'users#follower', as:'follower'
  get 'search' => 'searchs#search', as:'search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  #いいねしているかどうか
  def favorited_by?(user)
  	favorites.where(user_id: user.id).exists?
  end
  #
  validates :body, length: {maximum: 200}
  validates :title, presence: true
  validates :body, presence: true

  #検索機能
  def Book.search(term, how_search)
    if how_search == "perfect"
      Book.where(title: term)
    elsif how_search == "front"
      Book.where(['title LIKE ?', "#{term}%"])
    elsif how_search == "back"
      Book.where(['title LIKE ?', "%#{term}"])
    elsif how_search == "part"
      Book.where(['title LIKE ?', "%#{term}%"])
    else
      Book.all
    end
  end
  #
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

	belongs_to :user
	belongs_to :book

	#空のコメントは削除できない事
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :book

	#一人が一つの投稿に対して、一つだけいいねを付けられる。book_idとuser_idの組が1組しかないようにバリデーション
	validates_uniqueness_of :book_id, scope: :user_id

end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :user
	belongs_to :follow, class_name: 'User'
	#Userモデルを参照する

	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  validates :introduction, length: {maximum: 50}
  validates :name, length: {in: 2..20}
  validates :name, presence: true

  #フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  #through:sourceとセットのこと多い。多対多で中間テーブルが複数ある場合、throughオプションで中間テーブルを指定すれば、経路を決めることができる。
  #source:class_nameとほぼ同じらしい。throughを使うような中間テーブルがある場合はsource。一対多のような中間テーブルを使わない場合はclass_nameらしい。
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  #class_name:一つのモデルに対して二つのアソシエーション経路を組む場合に多用
  #foreign_key:難しい
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  #検索機能でselectの時に記述
  def User.search(term, how_search)
    if how_search == "perfect"
      User.where(name: term)
    elsif how_search == "front"
      User.where(['name LIKE ?', "#{term}%"])
    elsif how_search == "back"
      User.where(['name LIKE ?', "%#{term}"])
    elsif how_search == "part"
      User.where(['name LIKE ?', "%#{term}%"])
    else
      User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]
  def after_sign_in_path_for(resource)
    user_path(current_user.id) # ログイン後に遷移するpathを設定
  end
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def set_book
    @book = current_user.books.find(params[:id])
  end

  def show
    @book = Book.find(params[:id])
    @comment = BookComment.new
    @book_new = Book.new
    @user = @book.user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully'
      redirect_to book_path(@book.id)
    else
      @book_new = Book.new
      @user = current_user
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless @book.user.id == current_user.id
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully'
      redirect_to book_path(@book.id)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def index
    @book =Book.new
    @user = current_user
    @users = User.all
    @books = Book.page(params[:page]).reverse_order
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController

	def search
		#Viewのformで取得したパラメータをモデルに渡す
		if params[:option] == "user"
			@users = User.search(params[:term], params[:choice])
			#render 'users/index',indexに検索結果のuserだけ表示される。
		elsif params[:option] == "book"
			@books = Book.search(params[:term], params[:choice])
			@books = @books.page(params[:page])
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
  	#マイページ
    @user = User.find(params[:id])
    #新規投稿
    @book = Book.new
    #current_userのデータだけ引っ張ってくる
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user.id == current_user.id
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully'
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def follow
    @user = User.find(params[:id])
    @follow_users = @user.followings
  end

  def follower
    @user = User.find(params[:id])
    @follower_users = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <header class="navbar navbar-inverse">
          <nav class = "nav navbar-nav navbar-left">
            <span class = "head">Bookers</span>
          </nav>
          <nav>
            <ul class = "nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to 'Home', user_path(current_user.id), class:"glyphicon glyphicon-home  aria-hidden=true"%></li>
                <li><%= link_to 'Users', users_path, class:"glyphicon glyphicon-user aria-hidden= true" %></li>
                <li><%= link_to 'Books', books_path, class:"glyphicon glyphicon-book aria-hidden=true" %></li>
                <li><%= link_to 'logout', destroy_user_session_path, class:"glyphicon glyphicon-log-out aria-hidden=true", method: :delete%></li>
              <%else%>
                <li><%= link_to 'Home', root_path, class:"glyphicon glyphicon-home  aria-hidden=true" %></li>
                <li><%= link_to 'About', home_about_path, class:"glyphicon glyphicon-link aria-hidden= true"%></li>
                <li><%= link_to 'sign up', new_user_registration_path, class:"glyphicon glyphicon-edit aria-hidden=true" %></li>
                <li><%= link_to 'login', new_user_session_path, class:"glyphicon glyphicon-log-in aria-hidden= true"%></li>
              <%end%>
            </ul>
          </nav>
        </header>
      </div>
    </div>
    <div class = "container">
      <%= yield %>
    </div>
    <footer>
      <div class = "container">
        <div class = "row">
          <div class = "col-md-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>